import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import AdminSidebar from '@/components/admin/AdminSidebar';
import AdminWorkspaceHeader from '@/components/admin/AdminWorkspaceHeader';
import ProductFormClient from '@/components/admin/ProductFormClient';
import OrdersClient from '@/components/admin/OrdersClient';
import ShippingFlowClient from '@/components/admin/ShippingFlowClient';
import KakaoCommercePanel from '@/components/admin/KakaoCommercePanel';
import {SiteProvider} from '@/components/SiteContext';
import type {SiteKey} from '@/lib/sites';
import {usePathname,navigate} from './navigation';
let previewSite:SiteKey='sanjipick';
const statuses=['paid','confirmed','preparing','shipped','delivered'];
const products=['제철 사과 3kg','손질 고등어 6팩','국내산 고구마 3kg','프리미엄 견과 세트','산지 직송 배 5kg'];
function orders(){return statuses.map((status,i)=>({id:`00000000-0000-4000-8000-00000000000${i}`,site:previewSite,order_number:`PREVIEW-0909-${i+1}`,status,order_type:'shop',buyer_name:'예시 고객 '+(i+1),buyer_phone:'010-0000-0000',recipient_name:'예시 수령인',recipient_phone:'010-0000-0000',addr_zipcode:'00000',addr_address:'미리보기 배송지',addr_detail:'예시 주소',addr_memo:null,total_amount:32900+i*4000,shipping_fee:3000,tracking_company:i>=3?'04':null,tracking_number:i>=3?'00123456789'+i:null,influencer_name:null,created_at:'2026-09-09T00:00:00Z',paid_at:'2026-09-09T00:00:00Z',payment_verified:true,pending_refunds:false,items:[{id:`item${i}`,product_id:`product${i}`,product_name:products[i],product_code:'P'+i,option_label:'기본 구성',unit_price:29900+i*4000,quantity:1,supplier_name:'예시 공급사',expected_ship_date:'2026-09-10'}]}));}
window.fetch=async(input,init)=>{const url=String(input);if(init?.method&&!['GET','HEAD'].includes(init.method.toUpperCase()))return Response.json({error:'미리보기에서는 실제 저장·발송을 실행하지 않습니다.'},{status:409});if(url.includes('/api/admin/orders'))return Response.json(orders());if(url.includes('/carriers'))return Response.json({keyMissing:true,carriers:[{code:'04',name:'CJ대한통운'},{code:'05',name:'한진택배'}]});if(url.includes('/categories'))return Response.json([{id:'1',name:previewSite==='sanjipick'?'산지픽 농산물':'식품'}]);return Response.json([]);};
function Summary(){return <><h1>{previewSite==='sanjipick'?'산지픽 오늘의 운영':'블랜드픽 오늘의 운영'}</h1><p style={{margin:'8px 0 22px',color:'#647182'}}>2026.09.09 · 설명용 예시 데이터</p><div className="preview-kpis">{[['신규 주문','2건'],['출고 준비','1건'],['배송중','1건'],['오늘 결제액','204,500원']].map(([label,value])=><button key={label} onClick={()=>navigate(label.includes('결제')?'/admin/settlements':'/admin/shipments')}><span>{label}</span><strong>{value}</strong><small>관련 업무 보기 →</small></button>)}</div><section className="commerce-panel"><h2>먼저 처리할 일</h2>{[['신규 주문 확인','결제·주소·수량 확인 후 발주 확정','/admin/orders'],['출고 준비','택배사 양식 준비와 송장 입력','/admin/shipments'],['카카오 연결 준비','배송 시작 안내부터 순서대로 연결','/admin/notifications']].map(([a,b,url])=><button className="preview-task" onClick={()=>navigate(url)} key={a}><b>{a}</b><span>{b}</span><span>확인 →</span></button>)}</section><section className="commerce-panel"><h2>업무를 이어서 처리하세요</h2><div className="commerce-flow-links">{[['상품 등록','products/new'],['전체 주문','orders'],['출고·배송','shipments'],['결제 정산','settlements']].map(([title,url])=><a key={url} href={'#'+encodeURIComponent('/admin/'+url)}>{title} →</a>)}</div></section></>;}
function ProductList(){const [q,setQ]=useState(''),[stage,setStage]=useState('전체');return <><div className="preview-title"><h1>상품 조회·수정</h1><button onClick={()=>navigate('/admin/products/new')}>+ 상품 등록</button></div><section className="commerce-panel"><div className="commerce-options">{['전체','판매 준비','판매중','품절'].map(x=><button key={x} aria-pressed={x===stage} onClick={()=>setStage(x)}>{x}</button>)}</div><label>상품명 검색 <input value={q} onChange={e=>setQ(e.target.value)} placeholder="예: 사과" style={{border:'1px solid #ccc',padding:10}}/></label></section><section className="commerce-panel commerce-table-wrap"><table><thead><tr><th>상품명</th><th>판매가</th><th>재고</th><th>판매 상태</th><th>전시</th><th>수정</th></tr></thead><tbody>{products.filter((n,i)=>n.includes(q)&&(stage==='전체'||stage===(i===4?'품절':i===3?'판매 준비':'판매중'))).map(n=>{const i=products.indexOf(n);return <tr key={n}><td>{n}</td><td>{(29900+i*4000).toLocaleString()}원</td><td>{i===4?0:24+i}개</td><td>{i===4?'품절':i===3?'판매 준비':'판매중'}</td><td>{i===3?'비전시 링크':'전시'}</td><td><button onClick={()=>navigate('/admin/products/new')}>등록 양식 보기</button></td></tr>;})}</tbody></table></section></>;}
function Settlement(){return <><h1>결제 정산</h1><p style={{margin:'8px 0 24px'}}>예시 금액 · 실제 입금 내역과 무관합니다.</p><div className="preview-kpis">{[['결제액','204,500원'],['환불액','0원'],['수수료 추정','6,135원'],['정산 예상','198,365원']].map(([x,y])=><div key={x}><span>{x}</span><strong>{y}</strong></div>)}</div><section className="commerce-panel"><h2>건별 정산</h2><div className="commerce-table-wrap"><table><thead><tr><th>주문번호</th><th>결제액</th><th>정산 상태</th><th>확인</th></tr></thead><tbody>{orders().map(o=><tr key={o.id}><td>{o.order_number}</td><td>{o.total_amount.toLocaleString()}원</td><td>{o.status==='delivered'?'정산 집계 대상':'배송완료 대기'}</td><td><button onClick={()=>navigate('/admin/orders')}>주문 확인</button></td></tr>)}</tbody></table></div></section></>;}
function App(){const [site,setSite]=useState<SiteKey>('sanjipick');previewSite=site;const path=usePathname();return <><div className="preview-banner"><strong>관리자 개편 미리보기</strong><span>예시 데이터 · 실제 저장/결제/문자 발송 없음</span><select aria-label="미리보기 사이트" value={site} onChange={e=>setSite(e.target.value as SiteKey)}><option value="blendpick">블랜드픽</option><option value="sanjipick">산지픽</option></select></div><SiteProvider site={site}><div className="admin-commerce"><AdminSidebar key={site} siteKey={site}/><main className="commerce-main"><AdminWorkspaceHeader siteKey={site}/><div className="commerce-content" key={path+site}>{path==='/admin/notifications'?<KakaoCommercePanel siteName={site==='sanjipick'?'산지픽':'블랜드픽'} channelUrl={null} sharedChannel={true}/>:path==='/admin/products/new'?<ProductFormClient mode="new"/>:path==='/admin/products'?<ProductList/>:path==='/admin/orders'?<OrdersClient sharedOrders={orders() as any}/>:path==='/admin/shipments'?<ShippingFlowClient/>:path==='/admin/settlements'||path==='/admin/profit'||path==='/admin/influencer-settlements'||path==='/admin/link-sales'?<Settlement/>:path==='/admin'||path==='/admin/operations'?<Summary/>:<section className="commerce-panel"><h1>관련 업무</h1><p>이 파일에서는 운영 홈·상품 목록·상품 등록·주문·배송·정산·카카오 화면을 확인할 수 있습니다. 다른 업무의 기존 기능은 관리자에서 유지됩니다.</p><div className="commerce-flow-links"><a href={'#'+encodeURIComponent('/admin')}>운영 홈</a><a href={'#'+encodeURIComponent('/admin/notifications')}>카카오 연동안</a></div></section>}</div></main></div></SiteProvider></>;}
createRoot(document.getElementById('app')!).render(<App/>);
