const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite'),{service}=require('../lib/dangung-core.cjs');
test('Cycle 2: isolated PostgreSQL booking/payment lifecycle (no live PG or gateway)',async t=>{
 const db=new PGlite();let queue=Promise.resolve(),clock=new Date('2026-09-14T00:00:00Z'),confirmCalls=0,cancelCalls=0,timeout=false,failSave=false,paymentOverride=null;const payments=new Map();
 const query=async(sql,args)=>{if(failSave&&sql.includes("SET status='paid'")){failSave=false;throw Error('simulated database outage after approval');}return db.query(sql,args);};
 const pool={query,connect:async()=>{const previous=queue;let release;queue=new Promise(r=>release=r);await previous;return {query,release};}};
 const gateway={confirm:async p=>{confirmCalls++;let saved=payments.get(p.orderId);if(!saved){saved={orderId:p.orderId,totalAmount:p.amount,currency:'KRW',paymentKey:p.paymentKey,status:'DONE',receipt:{url:'https://example.com/test-receipt'}};payments.set(p.orderId,saved);}if(timeout){timeout=false;throw Error('simulated timeout after approval');}return paymentOverride?{...saved,...paymentOverride}:saved;},lookup:async id=>{if(!payments.has(id))throw Error('not found');return payments.get(id);},cancel:async(key,amount,reason,id)=>{cancelCalls++;const p=payments.get(id);p.status=amount===p.totalAmount?'CANCELED':'PARTIAL_CANCELED';p.cancels=[{cancelAmount:amount}];return p;}};
 const api=service(pool,gateway,{now:()=>clock}),owner='test-owner-A',other='test-owner-B';
 const config={enabled:true,extraGuestFee:20000,extraGuestUnit:'perNight',bbqFee:50000,depositAmount:100000,depositTerms:'격리 테스트 보증금 조건입니다. 실판매에 사용하지 않습니다.',refundTerms:'격리 테스트 환불 규정입니다. 실판매에 사용하지 않습니다.',minLeadDays:1,maxNights:7};
 const request=async(day='2026-09-15',extra={})=>{const input={checkIn:day,checkOut:new Date(Date.parse(day)+86400000).toISOString().slice(0,10),guests:6,bbq:false,...extra},q=await api.getQuote(input);return {...input,requestId:randomUUID(),buyerName:'테스트예약',buyerPhone:'01012345678',memo:'test only',version:q.version,amount:q.total,agreed:true};};
 const confirmation=r=>({orderId:r.id,paymentKey:'test_payment_'+r.id,amount:r.amount});
 try{
 await t.test('migration is repeatable and starts with sales disabled and no prices',async()=>{const sql=fs.readFileSync(path.join(__dirname,'../scripts/dangung.sql'),'utf8');await db.exec(sql);await db.exec(sql);const c=await api.calendar();assert.equal(c.config.enabled,false);assert.equal(c.dates.length,0);await assert.rejects(api.getQuote({checkIn:'2026-09-15',checkOut:'2026-09-16',guests:6,bbq:false}));});
 await api.settings(config);await api.setDates({start:'2026-09-15',end:'2026-10-15',weekdayPrice:450000,weekendPrice:540000,season:'테스트',available:true});
 let first,firstInput;
 await t.test('reservation snapshots terms, places one hold, repeats without duplication',async()=>{firstInput=await request();first=await api.reserve(firstInput,owner);const second=await api.reserve(firstInput,owner);assert.equal(first.id,second.id);assert.equal((await db.query('SELECT count(*)::int n FROM dangung_occupancy')).rows[0].n,1);assert.equal(first.quote.refundTerms,config.refundTerms);});
 await t.test('foreign owner cannot read, confirm or abandon a reservation',async()=>{await assert.rejects(api.status(first.id,other));await assert.rejects(api.confirm(confirmation(first),other));await assert.rejects(api.abandon(first.id,other));assert.equal(confirmCalls,0);});
 await t.test('amount tampering and reused request with changed payload rejected before gateway',async()=>{await assert.rejects(api.confirm({...confirmation(first),amount:1},owner));await assert.rejects(api.reserve({...firstInput,buyerPhone:'01022223333'},owner));assert.equal(confirmCalls,0);});
 await t.test('held night unavailable to another buyer; no second record',async()=>{await assert.rejects(api.getQuote({checkIn:'2026-09-15',checkOut:'2026-09-16',guests:6,bbq:false}));const old={...firstInput,requestId:randomUUID()};await assert.rejects(api.reserve(old,other));assert.equal((await db.query('SELECT count(*)::int n FROM dangung_reservations')).rows[0].n,1);});
 await t.test('approval stored once; duplicate callbacks never call gateway again',async()=>{const paid=await api.confirm(confirmation(first),owner);assert.equal(paid.status,'paid');await api.confirm(confirmation(first),owner);assert.equal(confirmCalls,1);assert.equal((await api.abandon(first.id,owner)).status,'paid');});
 await t.test('concurrent buyers for same night: only one transaction succeeds',async()=>{const r=await request('2026-09-17'),results=await Promise.allSettled([api.reserve(r,owner),api.reserve({...r,requestId:randomUUID()},other)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await db.query("SELECT count(*)::int n FROM dangung_occupancy WHERE day='2026-09-17'")).rows[0].n,1);});
 await t.test('pending hold expires after 15 minutes; late callback cannot charge',async()=>{const r=await api.reserve(await request('2026-09-18'),other);clock=new Date(clock.getTime()+16*60000);const calls=confirmCalls;assert.equal((await api.status(r.id,other)).status,'expired');await assert.rejects(api.confirm(confirmation(r),other));assert.equal(confirmCalls,calls);assert.ok((await api.getQuote({checkIn:'2026-09-18',checkOut:'2026-09-19',guests:6,bbq:false})).total);});
 await t.test('gateway timeout after payment preserves inventory and recovers by lookup',async()=>{const r=await api.reserve(await request('2026-09-19'),other);timeout=true;await assert.rejects(api.confirm(confirmation(r),other));clock=new Date(clock.getTime()+30*60000);assert.equal((await api.status(r.id,other)).status,'confirming');await assert.rejects(api.getQuote({checkIn:'2026-09-19',checkOut:'2026-09-20',guests:6,bbq:false}));const calls=confirmCalls;assert.equal((await api.reconcile(r.id,other)).status,'paid');assert.equal(confirmCalls,calls);});
 await t.test('database failure after approval rolls back and later lookup finishes booking',async()=>{const r=await api.reserve(await request('2026-09-20'),owner);failSave=true;await assert.rejects(api.confirm(confirmation(r),owner));assert.equal((await api.status(r.id,owner)).status,'confirming');assert.equal((await api.reconcile(r.id,owner)).status,'paid');});
 await t.test('mismatched gateway response never marks booking paid',async()=>{const r=await api.reserve(await request('2026-09-21'),other);paymentOverride={totalAmount:1};await assert.rejects(api.confirm(confirmation(r),other));assert.equal((await api.status(r.id,other)).status,'confirming');paymentOverride=null;await api.reconcile(r.id);});
 await t.test('settings version changes invalidate unreserved quotes but not paid snapshots',async()=>{const r=await request('2026-09-22');await api.settings({...config,refundTerms:'변경된 테스트 취소·환불 규정입니다. 실판매에 사용하지 않습니다.'});await assert.rejects(api.reserve(r,owner));assert.equal((await api.status(first.id,owner)).quote.refundTerms,config.refundTerms);});
 await t.test('customer requests cancellation; admin full refund releases date exactly once',async()=>{assert.equal((await api.requestCancel(first.id,owner)).cancelRequested,true);const cancelled=await api.cancel(first.id,first.amount,'테스트 전액 취소');assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.refundAmount,first.amount);await api.cancel(first.id,first.amount,'테스트 전액 취소');assert.equal(cancelCalls,1);assert.ok(await api.getQuote({checkIn:'2026-09-15',checkOut:'2026-09-16',guests:6,bbq:false}));});
 await t.test('partial refund closes reservation, retains fee and frees room',async()=>{const r=await api.reserve(await request('2026-09-23'),owner);await api.confirm(confirmation(r),owner);const cancelled=await api.cancel(r.id,200000,'테스트 부분 환불');assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.refundAmount,200000);const a=await api.admin();assert.equal(Number(a.totals.retained_amount),r.amount-200000);});
 await t.test('zero-refund cancellation performs no gateway call and frees room',async()=>{const r=await api.reserve(await request('2026-09-24'),owner);await api.confirm(confirmation(r),owner);const calls=cancelCalls;assert.equal((await api.cancel(r.id,0,'테스트 노쇼 취소')).status,'cancelled');assert.equal(cancelCalls,calls);assert.ok(await api.getQuote({checkIn:'2026-09-24',checkOut:'2026-09-25',guests:6,bbq:false}));});
 await t.test('SQL unique occupancy prevents double allocation even outside application',async()=>{await assert.rejects(db.query('INSERT INTO dangung_occupancy(day,reservation_id) SELECT day,reservation_id FROM dangung_occupancy LIMIT 1'));});
 await t.test('schema rerun preserves enabled configuration and paid records',async()=>{await db.exec(fs.readFileSync(path.join(__dirname,'../scripts/dangung.sql'),'utf8'));assert.equal((await api.calendar()).config.enabled,true);assert.ok((await api.admin()).totals.paid_count>0);});
 }finally{await db.close();}
});
