const {test,before,beforeEach,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite'),{load}=require('./support/load.cjs'),setup=require('./support/integrity-schema.cjs');
const originalFetch=global.fetch;const db=new PGlite();let site='sanjipick',authorized=true;const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const query=async(sql,p=[])=>{const r=await db.query(sql,p);return {...r,rowCount:r.affectedRows??r.rows.length};};const pool={query,connect:async()=>({query,release(){}})};
const mocks={'@/lib/db-shop':pool,'@/lib/db':pool,'@/lib/site-server':{currentSite:async()=>({key:site})},'next/headers':{headers:async()=>new Headers({host:site==='sanjipick'?'sanjipick.blendpunch.com':'shop.blendpunch.com'}),cookies:async()=>({get:()=>authorized?{value:'test'}:undefined})},'@/lib/auth':{verifyToken:async()=>null,verifyAdminToken:async()=>authorized?{}:null}};
mocks['@/lib/sms']={phoneVerifyOn:()=>false};mocks['@/lib/phone-verify']={isPhoneVerified:async()=>false};mocks['@/lib/inf-ref']={infRefFromCookie:async()=>null};
const shipping=load('lib/shipping.ts'),{verifyCartAmount,quoteCartAmount,verifySingleAmount}=load('lib/order-amount.ts',mocks);
const req=b=>new Request('http://localhost/x',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});
before(async()=>{await setup(db,id);await db.exec(fs.readFileSync('scripts/admin-workflow.sql','utf8'));await db.exec(fs.readFileSync('scripts/shipping-fees.sql','utf8'));});
beforeEach(async()=>{site='sanjipick';authorized=true;global.fetch=async()=>{throw Error('External network blocked');};await db.exec('TRUNCATE products_shop,product_options,product_addons,orders,order_items CASCADE');});after(()=>{global.fetch=originalFetch;return db.close();});
async function product(n=1,overrides={}){await query("INSERT INTO products_shop(id,name,category,status,stock,price,supply_price,shipping_type,shipping_cost,tax_type,supplier_name,release_address,shipping_carrier) VALUES($1,'테스트','산지픽','active',100,20000,10000,'paid',3000,'taxable','농가A','출고지A','04')",[id(n)]);for(const[k,v]of Object.entries(overrides))await query(`UPDATE products_shop SET ${k}=$1 WHERE id=$2`,[v,id(n)]);}
const item=(n=1,quantity=1)=>({product_id:id(n),quantity});const params=(items=[item()],shippingZipcode='12345')=>({site,items,shippingZipcode,totalAmount:0,shippingCost:0,amount:0});
test('same supplier/address/carrier merges; different or missing grouping fields split',()=>{const a={product_id:'a',quantity:1,unit_price:10000,shipping_type:'paid',shipping_cost:3000,supplier_name:'A',release_address:'X',shipping_carrier:'04'};assert.equal(shipping.cartShippingFee([a,{...a,product_id:'b',shipping_cost:4000}]),4000);assert.equal(shipping.cartShippingFee([a,{...a,product_id:'b',supplier_name:'B',shipping_cost:4000}]),7000);assert.equal(shipping.cartShippingFee([a,{...a,product_id:'b',release_address:'Y'}]),6000);assert.equal(shipping.cartShippingFee([{...a,release_address:null},{...a,product_id:'b',release_address:null}]),6000);});
test('same product options aggregate per-unit quantities and free threshold',()=>{const a={product_id:'a',quantity:1,unit_price:10000,shipping_type:'per_unit',shipping_cost:0,per_unit_shipping_cost:3000};assert.equal(shipping.cartShippingFee([a,{...a,quantity:2}]),6000);assert.equal(shipping.cartShippingFee([{...a,shipping_type:'conditional_free',free_shipping_threshold:30000,shipping_cost:3000,quantity:3}]),0);});
test('postal ranges retain leading zeros and reject malformed bounds',()=>{assert.deepEqual(shipping.postalRanges('01234, 23400-23499'),[['01234','01234'],['23400','23499']]);for(const v of ['1234','23499-23400','abc','12345-'])assert.throws(()=>shipping.postalRanges(v));});
test('regional surcharge is once per bundle even for free shipping',async()=>{await product(1,{shipping_type:'free',island_shipping_cost:5000,remote_zipcodes:'12340-12349'});await product(2,{shipping_type:'free',island_shipping_cost:4000,remote_zipcodes:'12345'});const q=await quoteCartAmount(params([item(1),item(2)]));assert.equal(q.ok,true);assert.equal(q.quote.shippingCost,5000);assert.equal(q.quote.regionalCost,5000);const normal=await quoteCartAmount(params([item(1),item(2)],'99999'));assert.equal(normal.quote.shippingCost,0);});
test('installation is a separate server-created line, not an extra shipping fee',async()=>{await product(1,{installation_cost:10000});const q=await quoteCartAmount(params([item(1,2)]));assert.equal(q.quote.goodsAmount,40000);assert.equal(q.quote.installationCost,20000);assert.equal(q.quote.shippingCost,3000);assert.equal(q.quote.totalAmount,63000);assert.equal(q.snapshots.length,2);assert.equal(q.snapshots[1].productId,null);assert.equal(q.snapshots[1].commissionRate,0);assert.equal(q.snapshots[1].quantity,2);});
test('single and cart verification agree and reject omitted installation or regional fees',async()=>{await product(1,{installation_cost:10000,island_shipping_cost:5000,remote_zipcodes:'12345'});const cart={...params(),totalAmount:30000,shippingCost:8000,amount:38000};assert.equal((await verifyCartAmount(cart)).ok,true);assert.equal((await verifySingleAmount({site,productId:id(1),quantity:1,unitPrice:20000,shippingZipcode:'12345',totalAmount:38000,shippingCost:8000,amount:38000})).ok,true);assert.equal((await verifyCartAmount({...cart,shippingCost:3000,amount:33000})).ok,false);assert.equal((await verifyCartAmount({...cart,totalAmount:20000,amount:28000})).ok,false);assert.equal((await verifyCartAmount({...cart,shippingZipcode:undefined})).ok,false);});
test('quote reflects destination change and settings change without DB mutation',async()=>{await product(1,{island_shipping_cost:5000,remote_zipcodes:'12345'});const a=await quoteCartAmount(params());const b=await quoteCartAmount(params([item()],'99999'));assert.equal(a.quote.shippingCost,8000);assert.equal(b.quote.shippingCost,3000);await query('UPDATE products_shop SET shipping_cost=4000');assert.equal((await verifyCartAmount({...params(),totalAmount:20000,shippingCost:8000,amount:28000})).ok,false);assert.equal((await query('SELECT stock FROM products_shop')).rows[0].stock,100);assert.equal((await query('SELECT count(*) n FROM payment_attempts')).rows[0].n,0);});
test('regional fee without configured regions fails visibly instead of charging zero',async()=>{await product(1,{island_shipping_cost:5000});const q=await quoteCartAmount(params());assert.equal(q.ok,false);assert.match(q.error,/배송비 확인/);});
test('negative fees, fractional thresholds and unknown shipping types are rejected at admin API',async()=>{const route=load('app/api/admin/products/route.ts',mocks);const b={name:'입력 검증',category:'산지픽',price:20000,supply_price:10000,stock:10,shipping_type:'paid',shipping_cost:3000,options:[],addons:[]};for(const patch of [{shipping_cost:-1},{return_cost_oneway:-3000},{shipping_type:'bad'},{shipping_type:'conditional_free',free_shipping_threshold:-1},{shipping_type:'conditional_free',free_shipping_threshold:30000.5},{island_shipping_cost:5000},{island_shipping_cost:5000,remote_zipcodes:'bad'}])assert.equal((await route.POST(req({...b,...patch}))).status,400);assert.equal((await query('SELECT count(*) n FROM products_shop')).rows[0].n,0);});
test('valid admin shipping settings persist and survive migration replay',async()=>{const route=load('app/api/admin/products/route.ts',mocks);const b={name:'입력 검증',category:'산지픽',price:20000,supply_price:10000,stock:10,shipping_type:'paid',shipping_cost:3000,island_shipping_cost:5000,remote_zipcodes:'12345',installation_cost:10000,options:[],addons:[]};assert.equal((await route.POST(req(b))).status,201);await db.exec(fs.readFileSync('scripts/shipping-fees.sql','utf8'));assert.equal((await query('SELECT remote_zipcodes FROM products_shop')).rows[0].remote_zipcodes,'12345');});
test('quote API trusts host scope and rejects missing destination or cross-site product',async()=>{await product();const route=load('app/api/checkout/quote/route.ts',mocks);assert.equal((await route.POST(req({items:[item()],shippingZipcode:'12345'}))).status,200);assert.equal((await route.POST(req({items:[item()]}))).status,400);site='blendpick';assert.equal((await route.POST(req({items:[item()],shippingZipcode:'12345',site:'sanjipick'}))).status,400);});
test('expired non-display links cannot obtain a price quote',async()=>{await product(1,{is_visible:false,link_code:'old-link',link_start_at:'2020-01-01',link_end_at:'2020-02-01'});assert.equal((await quoteCartAmount(params([{...item(),link_code:'old-link'}]))).ok,false);assert.equal((await quoteCartAmount(params())).ok,false);});

test('direct multi-line checkout records delivery and installation once and shipping-deducted refund retains only delivery',async()=>{
 await product(1,{installation_cost:10000,island_shipping_cost:5000,remote_zipcodes:'12345'});
 const {NextRequest}=require('next/server');let approvals=0,refund=0;
 global.fetch=async(url,opts)=>{const b=JSON.parse(opts.body);if(url.endsWith('/confirm')){approvals++;return Response.json({paymentKey:b.paymentKey,orderId:b.orderId,totalAmount:b.amount,status:'DONE',method:'카드'});}if(url.endsWith('/cancel')){refund+=b.cancelAmount;return Response.json({paymentKey:'shipping-test',totalAmount:38000,balanceAmount:38000-refund,status:'PARTIAL_CANCELED'});}throw Error('Unexpected network');};
 const route=load('lib/shop-checkout.ts',mocks);const data={paymentKey:'shipping-test',orderId:'shipping-order',amount:38000,checkoutData:{fromCart:false,items:[{...item(),id:id(800)}],totalAmount:30000,shippingCost:8000,shippingZipcode:'12345',shippingAddress:'검증 주소',customerName:'테스트',customerPhone:'01000000000'}};
 const request=()=>new NextRequest('https://sanjipick.blendpunch.com/api/payment/cart-confirm',{method:'POST',headers:{host:'sanjipick.blendpunch.com','content-type':'application/json'},body:JSON.stringify(data)});
 const first=await route.shopCheckout(request(),'cart');assert.equal(first.status,200,JSON.stringify(await first.clone().json()));assert.equal((await route.shopCheckout(request(),'cart')).status,200);assert.equal(approvals,1);
 const order=(await query('SELECT * FROM orders')).rows[0];assert.equal(order.total_amount,38000);assert.equal(order.shipping_fee,8000);assert.equal((await query('SELECT count(*) n FROM order_items')).rows[0].n,2);assert.equal((await query('SELECT stock FROM products_shop')).rows[0].stock,99);
 const cancelled=await load('lib/order-cancel.ts',mocks).cancelShopOrder(order.id,'검증',{deductShipping:true,site});assert.equal(cancelled.ok,true);assert.equal(refund,30000);assert.equal((await query('SELECT stock FROM products_shop')).rows[0].stock,100);
});
