const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),zlib=require('node:zlib');
const {collect}=require('../scripts/traffic/live.cjs');const {inspectConfig}=require('../scripts/traffic/nginx-config.cjs');const {systemdQuote}=require('../scripts/install-traffic-monitor.cjs');
const {load}=require('./support/load.cjs');const {selectTraffic,getServerTraffic}=load('lib/server-traffic.ts');
const dump=(serverExtra='',httpExtra='')=>`# configuration file /etc/nginx/nginx.conf:\nevents {}\nhttp {access_log /var/log/nginx/access.log; include /etc/nginx/conf.d/*.conf; include /etc/nginx/sites-enabled/*; ${httpExtra}}\n# configuration file /etc/nginx/sites-enabled/shop:\nserver {listen 80; server_name shop.blendpunch.com; location / {proxy_pass http://localhost:3000;} ${serverExtra}}\n# configuration file /etc/nginx/sites-enabled/sanji:\nserver {listen 80;server_name sanjipick.blendpunch.com;}\n`;
const row=(site,time='2026-09-08T10:00:00+09:00')=>JSON.stringify({schema:1,time,site,client:'other',route:'home',method:'GET',status:'200',bytes:'1024',request_bytes:'256',seconds:'0.3',content_type:'text/html',prefetch:'0'});
async function fixture(fn){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bp-traffic-live-')),logDir=path.join(dir,'logs'),stateDir=path.join(dir,'state');fs.mkdirSync(logDir);fs.mkdirSync(stateDir);fs.writeFileSync(path.join(stateDir,'capture.json'),JSON.stringify({startedAt:'2026-09-08T00:00:00+09:00'}));try{await fn({dir,logDir,stateDir,now:new Date('2026-09-08T11:00:00+09:00')});}finally{fs.rmSync(dir,{recursive:true,force:true});}}
test('nginx includes 확장·두 도메인·기존 http 로그 상속 확인',()=>{const r=inspectConfig(dump());assert.equal(r.sites.length,2);assert.equal(r.overrides,0)});
test('server 또는 location 로그 재정의는 임의 덮어쓰기 금지',()=>{for(const s of ['access_log off;','location /x {access_log /x;}'])assert.throws(()=>inspectConfig(dump(s)),/overrides/)});
test('누락 도메인·conf.d 컨텍스트·깨진 설정 거부',()=>{assert.throws(()=>inspectConfig(dump().replace('sanjipick.blendpunch.com','unknown.invalid')),/Both/);assert.throws(()=>inspectConfig(dump().replace('include /etc/nginx/conf.d/*.conf;','')),/conf.d/);assert.throws(()=>inspectConfig(dump()+'server {'))});
test('따옴표 내 중괄호·주석이 parser를 깨지 않음',()=>{assert.equal(inspectConfig(dump('',`log_format x '{"key":"value"}'; # comment\n`)).sites.length,2)});
test('systemd 경로 공백·% quoting',()=>{assert.equal(systemdQuote('/home/x y/100%/node'),'"/home/x y/100%%/node"');assert.throws(()=>systemdQuote('/bad\npath'))});
test('실제 JSONL+압축 로테이션 집계와 관리자 사이트 분리',async()=>fixture(async o=>{fs.writeFileSync(path.join(o.logDir,'blendpick-traffic.jsonl'),row('blendpick')+'\n'+row('sanjipick')+'\n');fs.writeFileSync(path.join(o.logDir,'blendpick-traffic.jsonl-20260908.gz'),zlib.gzipSync(row('blendpick','2026-09-08T09:00:00+09:00')+'\n'));const r=await collect(o);const bp=selectTraffic(r,'blendpick',7,o.now),sj=selectTraffic(r,'sanjipick',7,o.now);assert.equal(bp.totals.requests,2);assert.equal(sj.totals.requests,1);assert.ok(!JSON.stringify(bp).includes('sanjipick'));assert.equal(bp.captureStartedAt,'2026-09-07T15:00:00.000Z');assert.equal(bp.effectiveFrom,bp.captureStartedAt);assert.ok(fs.existsSync(path.join(o.stateDir,'traffic-summary.json')))}));
test('쓰기 중 마지막 불완전 행은 제외·중복 inode 중복합산 방지',async()=>fixture(async o=>{const file=path.join(o.logDir,'blendpick-traffic.jsonl');fs.writeFileSync(file,row('blendpick')+'\n{"partial"');fs.linkSync(file,path.join(o.logDir,'blendpick-traffic.jsonl-20260908'));const r=await collect(o);assert.equal(r.ranges[0].sites[0].total.requests,1);assert.equal(r.fileCount,1);assert.equal(r.trailingLines,1)}));
test('같은 기간 재집계는 누적 가산 없이 교체',async()=>fixture(async o=>{fs.writeFileSync(path.join(o.logDir,'blendpick-traffic.jsonl'),row('blendpick')+'\n');await collect(o);await collect(o);const r=JSON.parse(fs.readFileSync(path.join(o.stateDir,'traffic-summary.json')));assert.equal(r.ranges[0].sites[0].total.requests,1)}));
test('오류 로그·파일 누락은 지난 정상 요약 보존',async()=>fixture(async o=>{fs.writeFileSync(path.join(o.stateDir,'traffic-summary.json'),'old');await assert.rejects(collect(o));fs.writeFileSync(path.join(o.logDir,'blendpick-traffic.jsonl'),'bad\n');await assert.rejects(collect(o),/Invalid traffic/);assert.equal(fs.readFileSync(path.join(o.stateDir,'traffic-summary.json'),'utf8'),'old')}));
test('관리자 시간 경과45분·누락/예시/비정상수치 거부',async()=>fixture(async o=>{fs.writeFileSync(path.join(o.logDir,'blendpick-traffic.jsonl'),row('blendpick')+'\n');const r=await collect(o);assert.equal(selectTraffic(r,'blendpick',1,new Date(+o.now+46*60000)).state,'stale');assert.throws(()=>selectTraffic({...r,mode:'example'},'blendpick',1,o.now));assert.throws(()=>selectTraffic(r,'blendpick',5,o.now));r.ranges[0].sites[0].total.requests=-1;assert.throws(()=>selectTraffic(r,'blendpick',1,o.now))}));
test('관리자 API 인증 없는 조회는 파일 접근 전에 차단',async()=>{let called=0;const GET=load('app/api/admin/traffic/route.ts',{'next/headers':{cookies:async()=>({get:()=>undefined})},'@/lib/auth':{verifyAdminToken:async()=>null},'@/lib/admin-site':{currentAdminSite:()=>{throw Error('unauthorized')}},'@/lib/server-traffic':{getServerTraffic:()=>called++}}).GET;assert.equal((await GET(new Request('https://shop.blendpunch.com/api/admin/traffic'))).status,401);assert.equal(called,0)});
test('관리자 API는 도메인 범위 유지·입력 site 무시',async()=>{const GET=load('app/api/admin/traffic/route.ts',{'next/headers':{cookies:async()=>({get:()=>({value:'valid'})})},'@/lib/auth':{verifyAdminToken:async()=>({id:'admin'})},'@/lib/admin-site':{currentAdminSite:async()=>({key:'sanjipick'})},'@/lib/server-traffic':{getServerTraffic:async(site,days)=>({site,days})}}).GET;const r=await GET(new Request('https://sanjipick.blendpunch.com/api/admin/traffic?site=blendpick&days=7'));assert.deepEqual(await r.json(),{site:'sanjipick',days:7});assert.equal((await GET(new Request('https://sanjipick.blendpunch.com/api/admin/traffic?days=999'))).status,400)});
