const LABELS = { pass: '정상', warn: '주의', fail: '실패', skip: '미검사' };
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function markdown(report) {
  const cell = x => String(x ?? '').replace(/[|\r\n]/g, ' ');
  const lines = ['# 블랜드픽 · 산지픽 자동 점검', '', report.mode === 'example' ? '**설명용 예시 · 운영 측정값 아님 · 정기 점검 미가동**' : `점검 시각: ${report.finishedAt}`, '',
    `정상 ${report.counts.pass} / 주의 ${report.counts.warn} / 실패 ${report.counts.fail} / 미검사 ${report.counts.skip}`, '',
    '| 사이트 | 항목 | 판정 | 응답 | 시도 | 원인 및 다음 행동 |', '|---|---|---|---|---|---|'];
  for (const site of report.sites) for (const row of site.checks) lines.push(`| ${cell(site.name)} | ${cell(row.title)} | ${LABELS[row.status]} | ${row.httpStatus ?? '—'} · ${row.durationMs == null ? '—' : Math.round(row.durationMs) + 'ms'} | ${row.attempts.length}회 | ${cell(row.issues.map(i => i.reason + ' → ' + i.action).join(' / ') || row.note || '점검 기준 충족')} |`);
  lines.push('', '공개 GET 응답과 비로그인 접근 차단만 확인합니다. 실제 로그인·결제·검색 색인·배송·문자 성공은 검증하지 않습니다. 상품 상세는 사이트당 최대 3개 표본이며 전체 링크 검사가 아닙니다.');
  if(report.traffic){lines.push('', '## 트래픽 · '+(report.traffic.mode==='example'?'설명용 예시':'입력 로그 집계'), '', '| 사이트 | 전체 요청 | 보낸 바이트 | HTML 문서 응답 | 서버 오류 |', '|---|---|---|---|---|');for(const s of report.traffic.sites)lines.push(`| ${cell(s.key)} | ${s.total.requests} | ${s.total.sentBytes} | ${s.total.htmlDocuments} | ${s.total.errors5xx} |`);lines.push('', '방문자·실제 페이지 조회수와 다릅니다. 로그 완전성 미확인. CDN 전체 사용량·비용 제외.');}
  return lines.join('\n') + '\n';
}
function html(report) {
  const example = report.mode === 'example';
  const cards = report.sites.flatMap(site => site.checks.map(row => `<article class="check ${esc(row.status)}" data-site="${esc(site.key)}" data-status="${esc(row.status)}"><div class="top"><span class="brand">${esc(site.name)}</span><b class="badge">${LABELS[row.status]}</b></div><h3>${esc(row.title)}</h3><a href="${esc(site.origin + row.path)}" target="_blank" rel="noopener noreferrer">${esc(row.path)}</a><div class="meta">HTTP ${row.httpStatus ?? '—'} · ${row.durationMs == null ? '측정 없음' : (row.durationMs / 1000).toFixed(2) + '초'} · ${row.attempts.length}회 시도</div>${row.issues.length ? row.issues.map(i => `<div class="reason"><strong>확인 사유</strong><p>${esc(i.reason)}</p><strong>다음 행동</strong><p>${esc(i.action)}</p></div>`).join('') : `<p class="note">${esc(row.note || '이번 점검 기준을 충족했습니다.')}</p>`}${row.attempts.length ? `<details><summary>시도별 기록 보기</summary>${row.attempts.map(a => `<p>${a.number}차 · HTTP ${a.httpStatus ?? '응답 없음'} · ${Math.round(a.durationMs)}ms · ${esc(a.issueCodes.join(', ') || '응답 기준 충족')}</p>`).join('')}</details>` : ''}</article>`)).join('');
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>자동 점검 상세 · 블랜드픽 · 산지픽</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f5f2;color:#172c29;font-family:system-ui,-apple-system,'Apple SD Gothic Neo',sans-serif;line-height:1.65}main{max-width:1200px;margin:auto;padding:44px 24px 80px}.eyebrow{font-weight:800;letter-spacing:.1em;color:#467064;font-size:12px}h1{font-size:38px;letter-spacing:-1.7px;margin:10px 0}h2{font-size:23px;letter-spacing:-.7px;margin-top:34px}.intro{color:#53645f;max-width:800px}.banner{background:#173e34;color:white;padding:20px 24px;border-radius:14px;margin:24px 0}.banner p{margin:5px 0 0;opacity:.85}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat{background:white;border:1px solid #dfe5df;padding:18px;border-radius:12px}.stat b{font-size:30px;display:block}.filters{display:flex;gap:16px;flex-wrap:wrap;margin:20px 0}label{font-size:14px;font-weight:700}select{margin-left:8px;padding:9px 12px;border:1px solid #c4cfc8;border-radius:8px;background:white;font:inherit}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.check{background:white;border:1px solid #dce4de;border-left:4px solid #3d8062;border-radius:12px;padding:22px;min-width:0}.check.warn{border-left-color:#c88d29}.check.fail{border-left-color:#c44941}.check.skip{border-left-color:#8b9691}.top{display:flex;justify-content:space-between;align-items:center}.brand{font-size:12px;font-weight:700;color:#657a71}.badge{background:#edf5ef;border-radius:30px;font-size:12px;padding:3px 11px}.warn .badge{background:#fff1d7;color:#815715}.fail .badge{background:#ffe9e6;color:#9d302a}.skip .badge{background:#edf0ed;color:#59655f}h3{font-size:20px;margin:9px 0 2px}a{color:#42685d;word-break:break-all;font-size:13px}.meta{font-size:13px;color:#697970;margin:12px 0}.reason{border-top:1px solid #e9eee9;padding-top:12px;margin-top:12px}.reason strong{font-size:12px;color:#5e6c64}.reason p{margin:3px 0 12px;font-size:14px}details{font-size:12px;color:#566b60}summary{cursor:pointer;padding:10px 0}.note{font-size:14px}.table-wrap{overflow-x:auto;background:white;border:1px solid #dce4de;border-radius:12px}table{border-collapse:collapse;width:100%;min-width:600px;text-align:left;font-size:14px}th,td{padding:14px 18px;border-bottom:1px solid #e4eae5}th{background:#eaf0eb}.limits{padding:20px 24px;background:#e9eeea;border-radius:12px;font-size:14px}.empty{display:none;background:white;padding:24px;border-radius:12px}.footer{color:#718078;font-size:12px;margin-top:30px}[hidden]{display:none!important}@media(max-width:700px){main{padding:25px 16px 50px}h1{font-size:29px}.grid{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}.check{padding:18px}.filters{display:grid}select{max-width:70%}}
</style></head><body><main><div class="eyebrow">BLENDPICK / SANJIPICK · OPERATIONS</div><h1>자동 점검, 문제가 보이면<br>다음 행동까지.</h1><p class="intro">사이트가 열리는지부터 상품 연결, 검색 수집 설정, 관리자 접근 차단까지. 사이트별 결과를 확인하고 문제가 있는 항목부터 처리하세요.</p><div class="banner"><strong>${example ? '설명용 예시 · 운영 측정값이 아닙니다' : '한 차례 실행한 점검 결과'}</strong><p>${example ? '이번 변경은 검토본입니다. 운영 배포와 정기 실행, 외부 알림 연결은 하지 않았습니다.' : '완료: ' + esc(report.finishedAt) + ' · 이 결과만으로 정기 점검 가동 여부를 판단할 수 없습니다.'}</p></div><div class="stats">${Object.entries(LABELS).map(([key,label]) => `<div class="stat">${label}<b>${report.counts[key]}</b>점검 항목</div>`).join('')}</div>
${require('../traffic/report.cjs').trafficHtml(report.traffic)}
<h2>확인할 항목</h2><div class="filters"><label>사이트<select id="site"><option value="all">두 사이트 전체</option value="blendpick">블랜드픽</option><option value="sanjipick">산지픽</option></select></label><label>결과<select id="status"><option value="all">전체 결과</option><option value="attention">주의·실패·미검사</option>${Object.entries(LABELS).map(([k,v]) => `<option value="${k}">${v}</option>`).join('')}</select></label><span id="visible" aria-live="polite"></span></div><div class="grid">${cards}</div><div class="empty" id="empty">선택한 조건에 해당하는 항목이 없습니다.</div>
<h2>언제, 어떤 기준으로 확인하나요?</h2><div class="table-wrap"><table><thead><tr><th>항목</th><th>점검 기준</th><th>실패 후 처리</th></tr></thead><tbody><tr><td>정기 실행</td><td>활성화 후 매시 17·47분, 약 30분 간격</td><td>${example ? '설명용 예시.' : '정기 실행 설정 적용.'} 실행 지연·누락은 별도 감시 필요</td></tr><tr><td>메인·목록·로그인 진입</td><td>HTTP 200, HTML·제목, 오류 화면 여부</td><td>경로·서버 상태 확인</td></tr><tr><td>상품 상세</td><td>공개 링크에서 사이트당 최대 3개</td><td>깨진 경로 확인. 표본 없으면 미검사</td></tr><tr><td>응답 지연</td><td>3초 이상 주의, 요청당 15초 제한</td><td>연결 실패·시간 초과·429·5xx만 1초 후 1회 재확인</td></tr><tr><td>검색 설정</td><td>noindex·robots 전체 차단·사이트맵 주소 검사</td><td>사이트별 검색 설정 확인</td></tr><tr><td>관리자 보호</td><td>비로그인 화면 차단·API 401/403</td><td>차단 실패는 우선 확인. 본문 수집 안 함</td></tr><tr><td>결과 보관</td><td>실행 요약 + HTML·JSON, 14일 보관 설정</td><td>실패 시 작업 실패로 표시. 메일·슬랙·문자 미연결</td></tr></tbody></table></div>
<h2>점검 결과를 읽는 방법</h2><div class="limits"><p><b>실패</b>는 접속 오류·깨진 상세·관리자 차단 실패처럼 우선 확인할 항목입니다. <b>주의</b>는 느린 응답·재확인 성공·검색 설정처럼 운영자가 의도를 확인할 항목입니다.</p><p>판매 준비 화면은 그 자체로 장애가 아닙니다. 상품 링크가 없으면 상세는 <b>미검사</b>로 남기며 정상이라고 표시하지 않습니다.</p><p>실제 로그인·결제 승인·주문/배송 처리·문자 발송·검색엔진 색인은 포함하지 않습니다. 브라우저 화면 렌더링, 사이트 간 상품 소속 대조, 모든 링크 검사도 별도입니다.</p><p><b>다음 단계:</b> 이전 실행과 비교한 장애 지속·복구 이력, 외부 알림과 실행 누락 감시는 아직 연결하지 않았습니다. 자동 복구·재배포도 수행하지 않습니다.</p></div><div class="footer">${example ? '표시된 응답 시간·상품 주소·장애는 설명용 예시입니다.' : '각 요청 시점의 응답 기준이며 서비스 전체 정상 여부를 보장하지 않습니다.'}</div></main><script>
function filter(){const site=document.getElementById('site').value,status=document.getElementById('status').value;let count=0;document.querySelectorAll('.check').forEach(el=>{const show=(site==='all'||site===el.dataset.site)&&(status==='all'||status===el.dataset.status||(status==='attention'&&el.dataset.status!=='pass'));el.hidden=!show;if(show)count++});document.getElementById('visible').textContent=count+'개 항목';document.getElementById('empty').style.display=count?'none':'block'}document.getElementById('site').addEventListener('change',filter);document.getElementById('status').addEventListener('change',filter);filter();
</script></body></html>`;
}
module.exports = { html, markdown };
