'use client';
import { useEffect,useRef,useState } from 'react';
import DangungPolicies from './Policies';
import { loadTossPayments } from '@tosspayments/tosspayments-sdk';
export const money=(n:number)=>`${n.toLocaleString('ko-KR')}원`;
export async function bookingApi(input:object){const r=await fetch('/api/dangung',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const data=await r.json();if(!r.ok)throw Error(data.error||'예약 처리에 실패했습니다.');return data;}
const dayKey=(d:Date)=>d.toISOString().slice(0,10);
const addDay=(d:string,n:number)=>dayKey(new Date(Date.parse(d)+n*86400000));
type Calendar={today:string;version:number;config:{enabled:boolean;minLeadDays:number;maxNights:number;extraGuestFee:number;extraGuestUnit:string;bbqFee:number;monitorFee:number;depositPaymentNote:string;depositAmount:number;depositTerms:string;refundTerms:string};dates:{day:string;price:number;season:string;available:boolean;occupied:boolean}[];paymentReady:boolean;phoneVerify:boolean};
type Quote={version:number;checkIn:string;checkOut:string;guests:number;infants:number;nightly:{day:string;price:number;season:string}[];lodging:number;extra:number;bbq:number;monitor:number;depositPaymentNote:string;total:number;depositAmount:number;depositTerms:string;refundTerms:string};
export default function DangungBooking({clientKey}:{clientKey:string}){
 const [calendar,setCalendar]=useState<Calendar|null>(null),[error,setError]=useState(''),[month,setMonth]=useState(0),[checkIn,setIn]=useState(''),[checkOut,setOut]=useState(''),[guests,setGuests]=useState(6),[bbq,setBbq]=useState(false),[monitor,setMonitor]=useState(false),[infants,setInfants]=useState(0),[buyerName,setName]=useState(''),[buyerPhone,setPhone]=useState(''),[memo,setMemo]=useState(''),[quote,setQuote]=useState<Quote|null>(null),[busy,setBusy]=useState(false),[agree,setAgree]=useState(false),[code,setCode]=useState(''),[verified,setVerified]=useState(false),[notice,setNotice]=useState('');
 const review=useRef<HTMLDialogElement>(null),requestId=useRef(''),pending=useRef(false);
 async function refresh(){const r=await fetch('/api/dangung',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setCalendar(d);return d as Calendar;}
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
 const selling=!!(calendar?.config.enabled&&calendar.paymentReady);
 const available=(day:string)=>selling&&day>=addDay(calendar!.today,calendar!.config.minLeadDays)&&calendar!.dates.some(d=>d.day===day&&d.available&&!d.occupied);
 function canOut(day:string){if(!checkIn||day<=checkIn||!calendar)return false;const count=(Date.parse(day)-Date.parse(checkIn))/86400000;return count<=calendar.config.maxNights&&Array.from({length:count},(_,i)=>addDay(checkIn,i)).every(available);}
 function choose(day:string){setQuote(null);setError('');requestId.current='';if(checkIn&&!checkOut&&day>checkIn){if(canOut(day))setOut(day);else setError('기간 중 마감된 날짜가 있습니다. 다른 입실일을 선택해 주세요.');}else{setIn(day);setOut('');}}
 async function phone(action:'send'|'confirm'){setBusy(true);setError('');try{const r=await fetch(action==='send'?'/api/verify/phone':'/api/verify/phone/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:buyerPhone,code})});const d=await r.json();if(!r.ok)throw Error(d.error);if(action==='confirm')setVerified(true);setNotice(action==='send'?'인증번호를 보냈습니다.':'휴대폰 인증이 완료되었습니다.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function reviewBooking(e:React.FormEvent){e.preventDefault();if(pending.current)return;setError('');if(!checkIn||!checkOut){setError('입실일과 퇴실일을 선택해 주세요.');return;}if(calendar?.phoneVerify&&!verified){setError('휴대폰 인증을 완료해 주세요.');return;}setBusy(true);try{const q=await bookingApi({action:'quote',checkIn,checkOut,guests,infants,bbq,monitor});setQuote(q);setAgree(false);review.current?.showModal();}catch(e){setError((e as Error).message);await refresh().catch(()=>{});}finally{setBusy(false);}}
 async function pay(){if(pending.current||!quote||!agree)return;pending.current=true;setBusy(true);setError('');let reservation:any;
 try{requestId.current||=crypto.randomUUID();reservation=await bookingApi({action:'reserve',requestId:requestId.current,checkIn,checkOut,guests,infants,bbq,monitor,buyerName,buyerPhone,memo,version:quote.version,amount:quote.total,agreed:true});
 if(reservation.status!=='pending'){location.assign(`/hotel/dangung/result?orderId=${reservation.id}`);return;}
 sessionStorage.setItem('dangung-last-reservation',reservation.id);
 const toss=await loadTossPayments(clientKey);await toss.payment({customerKey:'ANONYMOUS'}).requestPayment({method:'CARD',amount:{currency:'KRW',value:reservation.amount},orderId:reservation.id,orderName:`단궁 독채 숙박 ${reservation.checkIn} ~ ${reservation.checkOut}`,customerName:buyerName,customerMobilePhone:buyerPhone,successUrl:`${location.origin}/hotel/dangung/result`,failUrl:`${location.origin}/hotel/dangung/result?failed=1&reservationId=${reservation.id}`});
 }catch(e){const err=e as Error&{code?:string};if(reservation?.id&&['USER_CANCEL','PAY_PROCESS_CANCELED','PAY_PROCESS_ABORTED'].includes(err.code||'')){await bookingApi({action:'abandon',orderId:reservation.id}).catch(()=>{});requestId.current='';setError('결제를 취소했습니다. 날짜를 다시 확인하고 예약할 수 있어요.');}else setError(err.message||'결제 진행 상태를 확인해 주세요.');review.current?.close();await refresh().catch(()=>{});}finally{pending.current=false;setBusy(false);}}
 const current=calendar?new Date(`${calendar.today.slice(0,7)}-01T00:00:00Z`):new Date('2026-01-01T00:00:00Z');current.setUTCMonth(current.getUTCMonth()+month);
 const monthDays=new Date(Date.UTC(current.getUTCFullYear(),current.getUTCMonth()+1,0)).getUTCDate(),leading=current.getUTCDay();
 const prices=calendar?.dates.filter(d=>d.available&&!d.occupied&&d.day>=addDay(calendar.today,calendar.config.minLeadDays)).map(d=>d.price)||[];
 return <section id="booking" className="booking-section dg-booking-live"><div className="heading"><div><div className="eyebrow">STAY WITH US</div><h2 id="booking-heading" className="serif" tabIndex={-1}>단궁에서 보낼 하루,<br/>달력에서 골라보세요.</h2></div><p>{selling&&prices.length?<>1박 <strong>{money(Math.min(...prices))}부터</strong><br/>기준 6인 · 날짜별 요금 확인</>:<>예약 오픈 준비 중<br/>확정 요금과 판매일을 곧 안내합니다.</>}</p></div>
 {error&&<p className="booking-error" role="alert">{error} <button type="button" onClick={()=>{setError('');refresh().catch(e=>setError(e.message));}}>다시 불러오기 ↻</button></p>}
 {notice&&<p role="status">{notice}</p>}
 <div className="booking-layout"><div className="calendar-panel"><div className="calendar-head"><button type="button" aria-label="이전 달" disabled={!calendar||month===0||busy} onClick={()=>setMonth(m=>m-1)}>←</button><h3 aria-live="polite">{calendar?`${current.getUTCFullYear()}년 ${current.getUTCMonth()+1}월`:'달력 불러오는 중'}</h3><button type="button" aria-label="다음 달" disabled={!calendar||month>=12||busy} onClick={()=>setMonth(m=>m+1)}>→</button></div><div className="calendar-week" aria-hidden="true">{'일월화수목금토'.split('').map(d=><span key={d}>{d}</span>)}</div><div className="calendar-days" role="group" aria-label="숙박 날짜 선택">{calendar&&<>{Array.from({length:leading},(_,i)=><span key={`empty${i}`}/>)}{Array.from({length:monthDays},(_,i)=>{const day=dayKey(new Date(Date.UTC(current.getUTCFullYear(),current.getUTCMonth(),i+1))),row=calendar.dates.find(d=>d.day===day),out=!!(checkIn&&!checkOut&&day>checkIn&&canOut(day)),active=day===checkIn||day===checkOut,inside=!!(checkIn&&checkOut&&day>checkIn&&day<checkOut);return <button key={day} type="button" disabled={busy||(!available(day)&&!out)} className={`${active?'selected':''} ${inside?'in-range':''}`} aria-pressed={active||inside} aria-label={`${day}${out?' 퇴실일 선택 가능':row&&available(day)?` ${row.season} ${money(row.price)}`:' 예약 마감 또는 준비 중'}`} onClick={()=>choose(day)}><b>{i+1}</b><small className="day-price">{row&&available(day)?`${(row.price/10000).toLocaleString('ko-KR')}만`:out?'퇴실':'—'}</small></button>;})}</>}</div><p className="date-hint" role="status">{!selling?'예약 가능한 날짜가 열리면 1박 요금이 표시됩니다.':checkIn&&!checkOut?'퇴실일을 선택해 주세요. 퇴실일에는 숙박 요금이 붙지 않습니다.':'입실일을 먼저 선택한 후 퇴실일을 선택해 주세요.'}</p><div className="stay-date-cards"><div><small>입실 · 15:00</small><strong>{checkIn||'날짜 선택'}</strong></div><span>→</span><div><small>퇴실 · 11:00</small><strong>{checkOut||'날짜 선택'}</strong></div></div><button type="button" className="text-button" disabled={busy} onClick={()=>{setIn('');setOut('');requestId.current='';}}>날짜 다시 선택 ↺</button></div>
 <form className="booking-form" onSubmit={reviewBooking}><fieldset disabled={busy||!selling}><legend>단궁 독채 숙박</legend><p className="booking-small">기준 6인 · 최대 16인 · 반려동물 동반 불가</p><label>이용 인원 (36개월 이상)<select value={guests} onChange={e=>{setGuests(Number(e.target.value));requestId.current='';}}>{Array.from({length:16},(_,i)=><option key={i} value={i+1}>{i+1}인</option>)}</select></label><label>36개월 미만 유아 (무료)<input type="number" min={0} max={99} step={1} value={infants} onChange={e=>{setInfants(Number(e.target.value));requestId.current='';}}/></label><p className="booking-small">36개월 미만 유아는 기준·최대 인원에 포함되지 않습니다.</p>{selling&&<p className="booking-small">6인 초과 시 1인 {money(calendar!.config.extraGuestFee)} / {calendar!.config.extraGuestUnit==='perNight'?'1박당':'예약당'} · 침구 포함</p>}<h3 className="dg-options-title">추가 옵션</h3><label className="dg-check"><input type="checkbox" checked={bbq} onChange={e=>{setBbq(e.target.checked);requestId.current='';}}/>바비큐 세팅 · 예약당 {money(calendar?.config.bbqFee??50000)}</label><label className="dg-check"><input type="checkbox" checked={monitor} onChange={e=>{setMonitor(e.target.checked);requestId.current='';}}/>64인치 모니터 추가 · 예약당 {money(calendar?.config.monitorFee??50000)}</label><div className="buyer-row"><label>예약자명<input required minLength={2} maxLength={40} autoComplete="name" value={buyerName} onChange={e=>{setName(e.target.value);requestId.current='';}}/></label><label>휴대폰 번호<input required type="tel" inputMode="tel" autoComplete="tel" pattern="01[016789][0-9]{7,8}" maxLength={11} placeholder="01012345678" value={buyerPhone} onChange={e=>{setPhone(e.target.value.replace(/\D/g,''));setVerified(false);requestId.current='';}}/></label></div>{calendar?.phoneVerify&&<div className="dg-verify"><button type="button" onClick={()=>phone('send')}>인증번호 받기</button><label>인증번호<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value)}/></label><button type="button" onClick={()=>phone('confirm')}>{verified?'인증 완료':'인증 확인'}</button></div>}<label>요청사항 (선택)<textarea rows={2} maxLength={300} value={memo} onChange={e=>{setMemo(e.target.value);requestId.current='';}}/></label><button className="booking-primary" type="submit">{busy?'확인 중…':'요금 확인하고 예약하기 →'}</button></fieldset>{!selling&&<p className="dg-closed">현재 예약 결제는 오픈 준비 중입니다.<br/>촬영대관·숙박 일정은 <a href="http://pf.kakao.com/_VyING/chat" target="_blank" rel="noopener noreferrer">카카오 상담 ↗</a>으로 문의해 주세요.</p>}<a className="text-button" href="/hotel/dangung/result">내 예약 확인 →</a></form></div>
 <dialog ref={review} className="booking-dialog" aria-labelledby="dg-review-title"><button type="button" disabled={busy} className="dialog-close" aria-label="예약 확인 닫기" onClick={()=>review.current?.close()}>×</button><h2 id="dg-review-title">예약 내용을 확인해 주세요.</h2>{quote&&<><p>{quote.checkIn} → {quote.checkOut} · {quote.nightly.length}박 · {quote.guests}인{quote.infants>0?` + 36개월 미만 유아 ${quote.infants}명 (무료)`:""}</p><p>{buyerName} · {buyerPhone}</p><ul className="nightly-list">{quote.nightly.map(d=><li key={d.day}><span>{d.day} · {d.season}</span><b>{money(d.price)}</b></li>)}</ul><dl className="dg-quote"><div><dt>숙박료</dt><dd>{money(quote.lodging)}</dd></div><div><dt>추가 인원</dt><dd>{money(quote.extra)}</dd></div><div><dt>바비큐 세팅</dt><dd>{money(quote.bbq)}</dd></div><div><dt>64인치 모니터</dt><dd>{money(quote.monitor)}</dd></div><div className="booking-total"><dt>지금 결제할 금액</dt><dd>{money(quote.total)}</dd></div></dl><p>시설 보증금 {money(quote.depositAmount)} (위 결제 금액에 미포함)</p><p className="dg-preline">{quote.depositPaymentNote}</p><p className="dg-preline">{quote.depositTerms}</p><details className="dg-terms" open><summary>취소·환불 규정</summary><p className="dg-preline">{quote.refundTerms}</p></details><label className="dg-check"><input type="checkbox" disabled={busy} checked={agree} onChange={e=>setAgree(e.target.checked)}/>예약 내역, 시설 보증금 별도 납부 조건, 취소·환불 규정 및 예약 처리에 필요한 이름·연락처 수집에 동의합니다. <a href="/privacy" target="_blank" rel="noopener noreferrer">개인정보 처리방침 ↗</a></label><button className="booking-primary" disabled={!agree||busy} type="button" onClick={pay}>{busy?'결제창 연결 중…':`${money(quote.total)} 결제하기 →`}</button><p className="booking-small">결제 승인 완료 후 예약이 확정됩니다. 결제 진행 중에는 최대 15분간 날짜를 확보합니다.</p></>}</dialog>
 <DangungPolicies refundTerms={calendar?.config.refundTerms||undefined} depositTerms={calendar?.config.depositTerms||undefined} depositPaymentNote={calendar?.config.depositPaymentNote||undefined}/>
 </section>;
}
