'use client';
import { useEffect,useState } from 'react';
type Category={id:string;name:string;hidden:boolean;merged_into:string|null;product_count:number};
export default function CategoriesPage(){
 const [rows,setRows]=useState<Category[]>([]),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showHidden,setShowHidden]=useState(false),[targets,setTargets]=useState<Record<string,string>>({});
 async function load(){try{const r=await fetch('/api/admin/categories?all=1');if(!r.ok)throw Error('분류 조회 실패');setRows(await r.json());}catch{setError('분류를 불러오지 못했습니다. 다시 조회해주세요.');}}
 useEffect(()=>{void load();},[]);
 async function mutate(path:string,method:string,body:object){setBusy(true);setError('');try{const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||'처리 실패');await load();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 return <div className="max-w-4xl space-y-5"><a href="/admin/products" className="text-sm underline">← 상품 관리</a><h1 className="text-xl font-bold">상품 분류 정리</h1><p className="text-sm text-stone-500">자주 쓰는 분류만 등록 화면에 표시합니다. 숨겨도 기존 상품은 유지됩니다. 통합은 같은 사이트 내에서만 적용하며 상품 소속과 주문 이력은 바뀌지 않습니다.</p>
 {error&&<p role="alert" className="bg-red-50 text-red-700 p-4">{error}</p>}
 <form className="flex gap-2" onSubmit={async e=>{e.preventDefault();if(await mutate('/api/admin/categories','POST',{name}))setName('');}}><input aria-label="새 분류명" required maxLength={100} value={name} onChange={e=>setName(e.target.value)} className="border rounded-lg p-2" placeholder="새 상품 분류"/><button disabled={busy} className="bg-emerald-900 text-white rounded-lg px-4">추가</button><button type="button" onClick={load} className="border rounded-lg px-3">새로고침</button></form>
 <label className="block text-sm"><input type="checkbox" checked={showHidden} onChange={e=>setShowHidden(e.target.checked)}/> 숨김·통합 이력 보기</label>
 <div className="space-y-3">{rows.filter(r=>showHidden||!r.hidden).map(r=><div key={r.id} className="flex flex-wrap items-center gap-3 rounded-xl border bg-white p-4"><div className="mr-auto"><b>{r.name}</b><p className="text-xs text-stone-500 mt-1">상품 {r.product_count}개 · {r.merged_into?'다른 분류로 통합됨':r.hidden?'신규 선택에서 숨김':'사용 중'}</p></div>{!r.merged_into&&<><button disabled={busy} className="text-sm underline" onClick={()=>mutate('/api/admin/categories/'+r.id,'PATCH',{action:r.hidden?'show':'hide'})}>{r.hidden?'다시 사용':'숨기기'}</button><select aria-label={`${r.name} 통합 대상`} value={targets[r.id]||''} onChange={e=>setTargets({...targets,[r.id]:e.target.value})} className="border rounded-lg p-2 text-sm"><option value="">통합 대상 선택</option>{rows.filter(t=>t.id!==r.id&&!t.hidden&&!t.merged_into).map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select><button className="text-sm text-emerald-900" disabled={busy||!targets[r.id]} onClick={()=>{const t=rows.find(t=>t.id===targets[r.id]);if(t&&confirm(`${r.name}의 상품 ${r.product_count}개를 ${t.name} 분류로 옮기고 기존 분류를 숨길까요?`))void mutate('/api/admin/categories/'+r.id,'PATCH',{action:'merge',target_id:t.id,expected_count:r.product_count});}}>통합 적용</button></>}</div>)}</div>
 </div>;
}
