'use client';
import {useEffect,useState} from 'react';
import {apiErrorMessage,readApiJson} from '@/lib/api-error-message';
type Question={id:string;category:string;message:string;reply:string|null;order_number:string|null;product_name:string|null;public_requested:boolean;is_public:boolean;order_id:string|null};
type Notice={id:string;kind:string;title:string;status:string;last_error:string|null;provider_id:string|null;order_number:string|null;created_at:string};
type Data={questions:Question[];notifications:Notice[];late:{id:string;order_number:string;expected_date:string;reason:string}[];channels:Record<string,boolean>};
export default function CustomerCareClient({orderId='',orderNumber=''}:{orderId?:string;orderNumber?:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [selected,setSelected]=useState<Question|null>(null),[reply,setReply]=useState(''),[publish,setPublish]=useState(false);
 const [order,setOrder]=useState(orderId),[orderLabel,setOrderLabel]=useState(orderNumber),[date,setDate]=useState(''),[reason,setReason]=useState('');
 async function load(){setError('');try{setData(await readApiJson(await fetch('/api/admin/customer-care'),'고객 관리 정보를 불러오지 못했습니다.'));}catch(e){setData(null);setError(apiErrorMessage(e));}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(selected)document.getElementById("reply-editor")?.scrollIntoView({behavior:"smooth",block:"center"});},[selected]);
 async function save(body:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{await readApiJson(await fetch('/api/admin/customer-care',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),'요청을 처리하지 못했습니다.');setMessage('저장했습니다.');setSelected(null);await load();}catch(e){setError(apiErrorMessage(e));}finally{setBusy(false);}}
 const labels:Record<string,string>={pending:'발송 대기',sending:'접수 중',accepted:'업체 접수 · 결과 대기',delivered:'수신 완료',review:'이력 확인 필요',blocked:'채널 설정 필요',site_only:'사이트 알림',cancelled:'발송 취소'};
 return <div className="customer-care"><h2>문의·고객 알림</h2><p>문의 답변, 출고 일정 변경과 알림 처리 상태를 확인합니다.</p><div className="care-actions"><a href="/admin/notifications">알림톡 문안·채널</a><a href="/admin/shipment-notifications">배송 문자 확인</a><button disabled={busy} onClick={load}>새로고침</button></div>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {data&&<><section className="care-info"><h3>알림톡 연결 상태</h3><div className="care-actions">{Object.entries(data.channels).map(([kind,on])=><span key={kind}>{({paid:'주문',shipping:'출고',refund:'환불',delay:'일정 변경',restock:'재입고',opening:'공구 오픈',answer:'답변'} as Record<string,string>)[kind]}: {on?'설정됨':'설정 필요'}</span>)}</div><p className="care-muted">업체 접수와 실제 수신 완료를 구분합니다. 결과가 불명확한 알림은 자동으로 다시 보내지 않습니다.</p></section>
 <section className="care-info"><h3>고객 문의 ({data.questions.filter(q=>!q.reply).length}건 답변 대기)</h3>{data.questions.length===0&&<p>접수된 문의가 없습니다.</p>}{data.questions.map(q=><article className="care-row" key={q.id}><strong>{q.category} · {q.reply?'답변 완료':'답변 대기'}</strong><p>{q.order_number||q.product_name}</p><p className="whitespace-pre-wrap">{q.message}</p>{q.reply&&<div className="care-reply">{q.reply}</div>}<button disabled={busy} onClick={()=>{setSelected(q);setReply(q.reply||'');setPublish(q.is_public);}}>답변 작성·수정</button></article>)}</section>
 {selected&&<form id="reply-editor" className="care-form" onSubmit={e=>{e.preventDefault();void save({action:'reply',id:selected.id,reply,publish});}}><h3>선택한 문의 답변</h3><p>{selected.message}</p><label>답변<textarea required maxLength={3000} value={reply} onChange={e=>setReply(e.target.value)}/></label>{selected.public_requested&&!selected.order_id&&<label><input type="checkbox" checked={publish} onChange={e=>setPublish(e.target.checked)}/> 질문·답변에 개인정보가 없는 것을 확인했으며 상품 Q&amp;A에 공개합니다.</label>}<div className="care-actions"><button disabled={busy}>답변 저장</button><button type="button" onClick={()=>setSelected(null)}>닫기</button></div></form>}
 <section className="care-info"><h3>출고 일정 변경</h3><p>주문 관리의 ‘출고 일정 안내’에서 주문을 선택해주세요. 변경된 날짜와 사유는 고객 주문 내역에 표시됩니다.</p><form className="care-form" onSubmit={e=>{e.preventDefault();void save({action:'shipping-date',id:order,date,reason});}}><label>선택한 주문<input readOnly value={orderLabel||order} placeholder="주문 관리에서 선택"/></label><label>변경 출고일<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>고객에게 안내할 사유<textarea maxLength={300} required value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!order}>출고일 저장·안내 예약</button></form>
 {data.late.map(o=><p key={o.id}>{o.order_number} · 예정일 {o.expected_date} 경과 <button onClick={()=>{setOrder(o.id);setOrderLabel(o.order_number);setDate('');setReason(o.reason);}}>일정 변경</button></p>)}</section>
 <section className="care-info"><h3>최근 고객 알림</h3><p>설정 대기 건은 채널 설정 후 24시간 이내에만 재개할 수 있습니다. 발송 결과 확인 대상은 SOLAPI 내역을 대조해주세요.</p>{data.notifications.length===0&&<p>알림 내역이 없습니다.</p>}{data.notifications.map(n=><article className="care-row" key={n.id}><strong>{n.title} · {labels[n.status]}</strong><p>{n.order_number} · {new Date(n.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>{n.last_error&&<p>{n.last_error}</p>}{n.provider_id&&<p className="care-muted">발송 조회 ID: {n.provider_id}</p>}<div className="care-actions">{n.status==='blocked'&&<button disabled={busy||!data.channels[n.kind]} onClick={()=>save({action:'release-blocked',id:n.id})}>설정 확인 후 발송 재개</button>}{['review','accepted'].includes(n.status)&&<><button disabled={busy} onClick={()=>{if(confirm('SOLAPI에서 이 메시지의 실제 수신 완료를 확인했나요?'))void save({action:'resolve',id:n.id,status:'delivered',confirmed:true});}}>수신 확인 완료</button><button disabled={busy} onClick={()=>{if(confirm('공급자 발송 내역을 확인하고 이 알림의 추가 처리를 종료할까요?'))void save({action:'resolve',id:n.id,status:'cancelled',confirmed:true});}}>이력 확인 후 종료</button></>}</div></article>)}</section></>}
 </div>;
}
