'use client';
import {useState} from 'react';
import {KAKAO_SCENARIOS} from '@/lib/kakao-commerce';
export default function KakaoCommercePanel({siteName,channelUrl,sharedChannel}:{siteName:string;channelUrl:string|null;sharedChannel:boolean}) {
 const [selected,setSelected]=useState<string>('shipping'),[copied,setCopied]=useState('');
 const scenario=KAKAO_SCENARIOS.find(s=>s.key===selected)!;
 const message=scenario.message.replace('[브랜드명]',`[${siteName}]`);
 async function copy(){try{await navigator.clipboard.writeText(message);setCopied('문안을 복사했습니다.');}catch{setCopied('자동 복사가 지원되지 않습니다. 아래 문안을 선택해 복사해주세요.');}}
 return <div><div className="flex flex-wrap justify-between gap-3 mb-5"><div><h1>카카오 상담·알림</h1><p className="mt-2 text-gray-500">{siteName}의 상담 연결과 단계별 고객 안내</p></div><span className="commerce-chip">자동 발송 준비 전</span></div>
 <div className="commerce-note">아래 메시지는 검토용 문안입니다. 템플릿 승인·발송 업체 연결 전이며, 문안을 선택하거나 복사해도 메시지가 발송되지 않습니다.</div>
 <div className="commerce-two-col"><div><section className="commerce-panel"><h2>카카오 상담 연결</h2><p>{channelUrl?'현재 사이트에 설정된 상담 주소가 있습니다. 채널 운영·상담 가능 여부는 별도 확인이 필요합니다.':'유효한 카카오톡 채널 주소를 먼저 설정해주세요.'}</p>{sharedChannel&&<p className="mt-3">현재 두 사이트가 같은 상담 주소를 사용합니다. 상담을 분리하려면 산지픽 전용 채널을 지정해주세요.</p>}<div className="commerce-flow-links">{channelUrl&&<a href={channelUrl} target="_blank" rel="noreferrer">설정된 상담 채널 열기 ↗</a>}<a href="https://center-pf.kakao.com/" target="_blank" rel="noreferrer">카카오 채널 관리자 ↗</a></div></section>
 <section className="commerce-panel"><h2>우선 연결할 업무</h2><p>1. 배송 시작 안내 → 2. 주문 접수·환불 결과 → 3. 운영자 예외 알림 → 4. 재입고·공구 소식</p><p className="mt-3">{siteName === "산지픽" ? "출고일·도서산간 배송비·보관 방법·신선식품 품질 문의를 자주 묻는 질문으로 정리하고, 주문내역에서 상담으로 연결하는 구성을 권합니다." : "고객센터에는 출고일·배송비·반품 방법을 자주 묻는 질문으로 정리하고, 주문내역에서 상담으로 연결하는 구성을 권합니다."}</p></section></div>
 <section className="commerce-panel"><h2>메시지 미리보기</h2><div className="commerce-options">{KAKAO_SCENARIOS.map(s=><button type="button" key={s.key} aria-pressed={selected===s.key} onClick={()=>{setSelected(s.key);setCopied('');}}>{s.label}</button>)}</div><div className="commerce-message"><strong>{siteName} · 검토용 문안</strong><pre>{message}</pre><span className="commerce-chip">버튼 문구: {scenario.button}</span></div><div className="mt-4 flex gap-3 items-center"><button type="button" onClick={copy}>문안 복사</button><p role="status">{copied}</p></div></section></div>
 <section className="commerce-panel"><h2>알림이 필요한 시점과 준비사항</h2><div className="commerce-table-wrap"><table><thead><tr><th>알림</th><th>대상</th><th>발송 기준</th><th>기대 효과</th><th>연결 전 준비</th></tr></thead><tbody>{KAKAO_SCENARIOS.map(s=><tr key={s.key}><td>{s.label}</td><td>{s.audience}</td><td>{s.event}</td><td>{s.benefit}</td><td>{s.prerequisite}</td></tr>)}</tbody></table></div></section>
 <section className="commerce-panel"><h2>연결 후 적용할 처리 규칙</h2><p>주문 처리가 확정된 뒤 발송 대기열에 기록 → 같은 이벤트는 한 번만 발송 → 결과 수신 → 실패 건만 재시도. 문자 대체 발송은 채널별 중복을 막고, 결과가 불명확하면 먼저 조회합니다.</p><p className="mt-3">운영자 알림에는 고객 전화번호·주소를 넣지 않고 관리자 로그인 화면으로 연결합니다. 홍보성 알림은 수신 설정과 해지 이력을 별도로 관리합니다.</p><div className="commerce-flow-links"><a href="https://business.kakao.com/info/infotalk/" target="_blank" rel="noreferrer">알림톡 공식 안내 ↗</a><a href="https://developers.kakao.com/docs/ko/kakaotalk-message/common" target="_blank" rel="noreferrer">일반 메시지 API 범위 ↗</a><a href="https://business.kakao.com/info/brandmessage/" target="_blank" rel="noreferrer">브랜드 메시지 안내 ↗</a></div></section></div>;
}
