import TrafficCharts from '@/components/admin/charts/TrafficCharts';
import type { ServerTraffic } from '@/lib/server-traffic';
const num=(v:number)=>v.toLocaleString('ko-KR');
const bytes=(v:number)=>v>=1073741824?(v/1073741824).toFixed(2)+' GiB':v>=1048576?(v/1048576).toFixed(2)+' MiB':(v/1024).toFixed(1)+' KiB';
const time=(v:string)=>new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
const labels={ready:'집계 완료',stale:'갱신 지연',unavailable:'집계 결과 없음',error:'집계 확인 필요'};
const routes:Record<string,string>={home:'메인',products:'상품',login:'로그인',assets:'이미지·정적 파일',api:'일반 API',admin:'관리자',other:'기타'};
export default function ServerTrafficPanel({data}:{data:ServerTraffic}) {
  const total=data.totals;
  return <section className="space-y-4" aria-labelledby="traffic-title"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="traffic-title" className="text-lg font-semibold">서버 트래픽</h2><span className={`rounded-full px-3 py-1 text-xs ${data.state==='ready'?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-900'}`}>{labels[data.state]}</span></div>
    <p className="text-xs text-stone-500">최근 집계: {data.generatedAt?time(data.generatedAt):'기록 없음'} · 30분 간격 · 선택한 조회 기간 기준</p>
    {data.state!=='ready'&&<p role="status" className="rounded-lg bg-amber-50 p-4 text-sm text-amber-900">{data.state==='stale'?'45분 이상 새 집계가 없습니다. 마지막 정상 집계값을 표시합니다.':data.state==='error'?'최근 집계 또는 결과 조회에 문제가 있습니다. 표시된 값의 집계 시각을 확인해 주세요.':'아직 집계 파일을 읽지 못했습니다. 0건으로 계산하지 않습니다.'}</p>}
    {total&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['전체 요청',num(total.requests)+'건'],['보낸 데이터',bytes(total.sentBytes)],['서버 오류율',total.error5xxPercent===null?'—':num(total.error5xxPercent)+'%'],['평균 처리 시간',total.averageMs===null?'—':num(total.averageMs)+'ms']].map(([label,value])=><div key={label} className="rounded-xl border border-stone-200 bg-white p-5"><p className="text-xs text-stone-500">{label}</p><p className="mt-3 text-xl font-semibold tabular-nums">{value}</p></div>)}</div>
    <TrafficCharts key={data.days} data={data}/>
    <details className="rounded-xl border border-stone-200 bg-white p-4 text-sm"><summary className="cursor-pointer font-medium">요청 종류·화면별 상세표</summary><div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-stone-200 bg-white p-5"><h3 className="mb-3 text-sm font-semibold">요청 종류</h3><dl className="space-y-2 text-sm">{[['일반·미분류',total.otherRequests],['식별된 봇',total.botRequests],['자동 점검',total.monitorRequests],['3초 이상 요청',total.slowRequests]].map(([k,v])=><div key={k} className="flex justify-between"><dt className="text-stone-600">{k}</dt><dd>{num(Number(v))}건</dd></div>)}</dl></div><div className="overflow-hidden rounded-xl border border-stone-200 bg-white"><h3 className="px-5 py-4 text-sm font-semibold">어디에서 사용했나요?</h3><table className="w-full text-left text-sm"><thead className="bg-stone-50 text-xs text-stone-500"><tr><th className="px-5 py-2">구분</th><th className="px-5 py-2 text-right">요청</th><th className="px-5 py-2 text-right">전송량</th></tr></thead><tbody>{data.routes.map(r=><tr key={r.route} className="border-t border-stone-100"><td className="px-5 py-2">{routes[r.route]}</td><td className="px-5 py-2 text-right">{num(r.requests)}</td><td className="px-5 py-2 text-right">{bytes(r.sentBytes)}</td></tr>)}</tbody></table></div></div>
    </details><details className="rounded-xl border border-stone-200 bg-white px-5 py-4 text-sm"><summary className="cursor-pointer font-medium">시간대별 요청·전송량</summary><div className="max-h-80 overflow-auto"><table className="mt-3 w-full whitespace-nowrap text-left text-xs"><thead><tr><th className="py-2">한국시간</th><th className="text-right">요청</th><th className="text-right">전송량</th><th className="text-right">서버 오류</th></tr></thead><tbody>{data.hours.map(h=><tr key={h.hour} className="border-t border-stone-100"><td className="py-2">{time(h.hour)}</td><td className="text-right">{num(h.requests)}</td><td className="text-right">{bytes(h.sentBytes)}</td><td className="text-right">{num(h.errors5xx)}</td></tr>)}</tbody></table></div></details></>}
    <p className="text-xs leading-6 text-stone-500">수집 시작: {data.captureStartedAt?time(data.captureStartedAt):'확인 전'}. 수집 시작 이전의 기록은 포함하지 않습니다. 전체 요청에는 이미지·API·봇·관리자 요청이 포함됩니다. 서버 관측값으로, 방문자 수·CDN 전체 사용량·청구 요금과 다릅니다.</p>
  </section>;
}
