const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={blendpick:'블랜드픽',sanjipick:'산지픽'};
const routes={home:'메인',products:'상품',login:'로그인',assets:'이미지·정적 파일',api:'일반 API',admin:'관리자',other:'기타'};
const num=v=>Number(v).toLocaleString('ko-KR');
const gib=v=>(Number(v)/1073741824).toFixed(3)+' GiB';
const kst=v=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(v));
function trafficHtml(r){if(!r)return '';
 return `<section id="traffic"><h2>트래픽도 함께 확인</h2><div class="banner"><strong>${r.mode==='example'?'설명용 트래픽 예시 · 실제 이용량 아님':'입력한 서버 로그 집계'}</strong><p>${esc(kst(r.from))} ~ ${esc(kst(r.to))} · 한국시간 · 종료 시각 제외</p></div><p class="intro">요청 수는 방문자 수와 다릅니다. 이미지·API·검색봇·자동 점검도 서버를 사용하므로 전체 트래픽에는 포함하고, 요청 종류는 따로 보여줍니다.</p><div class="grid">${r.sites.map(s=>`<article class="check"><div class="brand">${esc(names[s.key]||s.key)}</div><h3>${num(s.total.requests)}건 요청</h3><p>보낸 데이터 <b>${gib(s.total.sentBytes)}</b> · 받은 데이터 ${gib(s.total.receivedBytes)}</p><div class="table-wrap"><table style="min-width:0"><tbody><tr><td>HTML 문서 응답</td><td>${num(s.total.htmlDocuments)}건</td></tr><tr><td>식별된 봇 / 자동 점검</td><td>${num(s.total.botRequests)} / ${num(s.total.monitorRequests)}건</td></tr><tr><td>그 외 요청</td><td>${num(s.total.otherRequests)}건</td></tr><tr><td>서버 오류 / 오류율</td><td>${num(s.total.errors5xx)}건 / ${s.total.error5xxPercent===null?'측정 없음':num(s.total.error5xxPercent)+'%'}</td></tr><tr><td>평균 처리 시간</td><td>${s.total.averageMs===null?'측정 없음':num(s.total.averageMs)+'ms'}</td></tr><tr><td>3초 이상 요청</td><td>${num(s.total.slowRequests)}건</td></tr><tr><td>방문자·세션·실제 페이지 조회수</td><td>별도 수집 필요</td></tr></tbody></table></div><details><summary>시간대별 요청·전송량 보기</summary><div class="table-wrap"><table style="min-width:0"><thead><tr><th>한국시간</th><th>요청</th><th>전송량</th><th>5xx</th></tr></thead><tbody>${s.hours.map(h=>`<tr><td>${esc(kst(h.hour))}</td><td>${num(h.requests)}</td><td>${gib(h.sentBytes)}</td><td>${num(h.errors5xx)}</td></tr>`).join('')}</tbody></table></div></details><details><summary>어디에서 트래픽을 쓰나요?</summary>${s.routes.map(x=>`<p>${esc(routes[x.route]||x.route)} · ${num(x.requests)}건 · ${gib(x.sentBytes)}</p>`).join('')}</details></article>`).join('')}</div><div class="limits" style="margin-top:20px"><p><b>수집 상태:</b> ${r.mode==='example'?'로그 수집 설정·집계 코드를 준비했으며 운영 수집은 미가동입니다.':'제공된 로그만 계산했습니다. 이 보고서는 정기 수집 상태를 확인하지 않습니다.'} 유효 ${num(r.quality.accepted)}행 / 잘못된 형식 ${num(r.quality.invalid)}행 / 알 수 없는 사이트 ${num(r.quality.unknownSite)}행.</p><p><b>빠진 로그를 0명으로 해석하지 않습니다.</b> 로그의 전체 기간 포함 여부는 미확인입니다. 기록이 없는 시간은 시간표에서 생략합니다.</p><p>HTML 문서 응답은 실제 페이지 조회수와 다릅니다. 앱 내부 화면 이동·브라우저 캐시·식별되지 않은 봇 때문에 차이가 납니다. 방문자·세션·유입 경로·구매 전환은 별도 브라우저 분석 수집이 필요합니다.</p><p>전송량은 이 서버가 관측한 값입니다. CDN에서 끝난 요청과 다른 저장소의 이미지 전송, 네트워크 계층 전체 사용량·실제 요금은 포함하지 않습니다. 새 로그에는 IP·쿠키·전체 URL·검색어·주문번호를 저장하지 않습니다.</p><p><a href="https://nginx.org/en/docs/http/ngx_http_log_module.html" target="_blank" rel="noopener noreferrer">측정 필드 기준: Nginx 공식 문서</a></p></div></section>`;
}
module.exports={trafficHtml};
